plugins {
    id 'maven-publish'
    id 'idea'
    id 'dev.sciwhiz12.gradle.simplversion' version '0.2.0'
    id 'net.neoforged.moddev' version '2.0.141'
}

versions {
    stripPattern = /^\d+\.\d+(\.[\dx]+)?-/
}
version = versions.version
println "Mod version: $version"

sourceSets {
    data.resources {
        srcDirs += 'src/data/clientResources'
        srcDirs += 'src/data/serverResources'
    }
    main.resources {
        srcDirs += data.resources.srcDirs
        exclude '.cache/'
    }
}

print "Java: ${System.getProperty('java.version')}"
print ", JVM: ${System.getProperty('java.vm.version')} (${System.getProperty('java.vendor')})"
println ", Arch: ${System.getProperty('os.arch')}"

neoForge {
    version = project.neoforge_version

    addModdingDependenciesTo(sourceSets.data)

    runs {
        configureEach {
            gameDirectory.set(project.file('run/' + it.name))
            logLevel = org.slf4j.event.Level.DEBUG
        }

        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }

        clientData {
            clientData()
            programArguments.addAll '--mod', modid, '--all'
            var srcDir = sourceSets.data.resources.srcDirs[1]

            programArguments.addAll '--output', srcDir.toString()
            for (var existingDir : (sourceSets.main.resources.srcDirs - srcDir)) {
                programArguments.addAll '--existing', existingDir.toString()
            }

            sourceSet = sourceSets.data
        }

        serverData {
            serverData()
            programArguments.addAll '--mod', modid, '--all'
            var srcDir = sourceSets.data.resources.srcDirs[2]

            programArguments.addAll '--output', srcDir.toString()
            for (var existingDir : (sourceSets.main.resources.srcDirs - srcDir)) {
                programArguments.addAll '--existing', existingDir.toString()
            }

            sourceSet = sourceSets.data
        }
    }

    mods {
        "$modid" {
            sourceSet(sourceSets.main)
            sourceSet(sourceSets.data)
        }
    }
}

configurations {
    dataImplementation.extendsFrom implementation
}

repositories {
    maven { // Repository for JEI
        name = "BlameJared"
        url = "https://maven.blamejared.com/"
        content {
            includeGroupAndSubgroups 'mezz.jei'
        }
    }
    maven { // Fallback repository for JEI
        name = 'ModMaven'
        url = 'https://modmaven.dev'
        content {
            includeGroupAndSubgroups 'mezz.jei'
        }
    }
}

base {
    archivesName = "${project.name}-${mc_version}"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(java_version)
    withSourcesJar()
}

dependencies {
    dataImplementation sourceSets.main.output

    compileOnly "mezz.jei:jei-${jei_mc_version}-neoforge-api:${jei_version}"
    runtimeOnly "mezz.jei:jei-${jei_mc_version}-neoforge:${jei_version}"
}

var manifestAttributes = [
        'Specification-Title'   : modid,
        'Specification-Vendor'  : author,
        'Specification-Version' : versions.rawVersion,
        'Implementation-Title'  : project.name,
        'Implementation-Version': project.version,
        'Implementation-Vendor' : author,
        "Git-Commit"            : versions.fullCommitId,
        "Git-Commit-Timestamp"  : versions.commitTimestamp
] as LinkedHashMap

tasks.withType(Jar).configureEach {
    manifest.attributes(manifestAttributes)
    includeEmptyDirs = false
    preserveFileTimestamps = false
    reproducibleFileOrder = true
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

publishing {
    publications.create('mavenJava', MavenPublication) {
        from components.java

        it.artifactId = project.name
        it.version = "$mc_version-$versions.simpleVersion"
    }

    repositories {
        maven {
            name = 'projectLocal'
            url = project.file('repo').absolutePath
        }
    }
}

idea {
    module {
        downloadSources = true
        downloadJavadoc = true
    }
}
