# suppress inspection "UnusedProperty" for whole file
org.gradle.caching=true
# org.gradle.configuration-cache=true # Disabled until simplversion is fixed to work with the configuration cache

# The information for the mod project
group=dev.sciwhiz12
modid=snowyweaponry
author=sciwhiz12

neogradle.subsystems.decompiler.maxMemory=3g

# Minecraft, NeoForge and Java versions
mc_version=1.21.8
neoforge_version=21.8.10
java_version=21

# Dependency versions
jei_mc_version=1.21.7
jei_version=23.1.0.4

parchment_minecraft_version=1.21.8
parchment_mappings_version=2025.07.20
