# suppress inspection "UnusedProperty" for whole file

# The information for the mod project
group=tk.sciwhiz12
modid=snowyweaponry
author=sciwhiz12

neogradle.subsystems.decompiler.maxMemory=3g

# Minecraft, NeoForge and Java versions
mc_version=1.20.4
neoforge_version=20.4.17-beta
java_version=17

# Logging markers and console logging level
logging_markers=REGISTRIES
logging_console=debug

# Dependency versions
jei_mc_version=1.20.2
jei_version=16.0.0.28
