# suppress inspection "UnusedProperty" for whole file
org.gradle.caching=true
# org.gradle.configuration-cache=true # Disabled until simplversion is fixed to work with the configuration cache

# The information for the mod project
group=dev.sciwhiz12
modid=snowyweaponry
author=sciwhiz12

neogradle.subsystems.decompiler.maxMemory=3g

# Minecraft, NeoForge and Java versions
mc_version=26.1
neoforge_version=26.1.0.17-beta
java_version=25

# Dependency versions
jei_mc_version=26.1
jei_version=29.2.0.1
