modLoader="javafml"
loaderVersion="[1,)"
license="MIT License"
issueTrackerURL="https://github.com/sciwhiz12/SnowyWeaponry/issues"

[[mods]]
modId="snowyweaponry"
version="${file.jarVersion}"
displayName="Snowy Weaponry"
displayURL="https://github.com/sciwhiz12/SnowyWeaponry"
credits="To the wonderful folks at MMD for WinterJam"
authors="§esciwhiz12§r"
description='''
Adds different snow-based weaponry. (and snow cones!)

§oThis mod was an entry for §2MMD§r's §bWinterJam 2020§r.
'''

[[dependencies.snowyweaponry]]
    modId="neoforge"
    type="required"
    versionRange="[20.6.7-beta,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowyweaponry]]
    modId="minecraft"
    type="required"
    versionRange="[1.20.6,1.20.7)"
    ordering="NONE"
    side="BOTH"

[[dependencies.snowyweaponry]]
    modId="jei"
    type="optional"
    versionRange="[16.0.0,18.0.0)"
    ordering="NONE"
    side="CLIENT"
